src/Entity/Film.php
<?php

namespace App\Entity;

use App\Film\Repository\FilmRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: FilmRepository::class)]
class Film
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[Assert\NotBlank]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[Assert\NotBlank]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $year = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $imgPath = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private ?bool $staff_favourite = false;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $date_add = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'film')]
    private Collection $comments;

    /**
     * @var Collection<int, FilmNote>
     */
    #[ORM\OneToMany(targetEntity: FilmNote::class, mappedBy: 'film', orphanRemoval: true)]
    private Collection $notes;

    /**
     * @var Collection<int, FilmGenre>
     */
    #[Assert\NotBlank]
    #[ORM\ManyToMany(targetEntity: FilmGenre::class, mappedBy: 'film', cascade: ['persist', 'remove'])]
    private Collection $genres;

    /**
     * @var Collection<int, City>
     */
    #[ORM\ManyToMany(targetEntity: City::class, mappedBy: 'film')]
    private Collection $cities;

    #[ORM\ManyToOne(inversedBy: 'id_film')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Rating $rating;

    /**
     * @var Collection<int, Seance>
     */
    #[ORM\OneToMany(targetEntity: Seance::class, mappedBy: 'id_film')]
    private Collection $seances;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->cities = new ArrayCollection();
        $this->seances = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function __toString(){
        return $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(string $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getImgPath(): ?string
    {
        return $this->imgPath;
    }

    public function setImgPath(string $imgPath): static
    {
        $this->imgPath = $imgPath;

        return $this;
    }

    public function getStaffFavourite(): ?bool
    {
        return $this->staff_favourite;
    }

    public function setStaffFavourite(?bool $staff_favourite): static
    {
        $this->staff_favourite = $staff_favourite;

        return $this;
    }

    public function getDateAdd(): ?\DateTimeImmutable
    {
        return $this->date_add;
    }

    public function setDateAdd(?\DateTimeImmutable $date_add): static
    {
        $this->date_add = $date_add;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setFilm($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getFilm() === $this) {
                $comment->setFilm(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, FilmNote>
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNotes(FilmNote $note): static
    {
        if (!$this->notes->contains($note)) {
            $this->notes->add($note);
            $note->setFilm($this);
        }

        return $this;
    }

    public function removeNote(FilmNote $note): static
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getFilm() === $this) {
                $note->setFilm(null);
            }
        }
        return $this;
    }


    /**
     * @return Collection<int, City>
     */
    public function getCities(): Collection
    {
        return $this->cities;
    }

    public function addCity(City $city): static
    {
        if (!$this->cities->contains($city)) {
            $this->cities->add($city);
            $city->addFilm($this);
        }

        return $this;
    }

    public function removeCity(City $city): static
    {
        if ($this->cities->removeElement($city)) {
            $city->removeFilm($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, FilmGenre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(FilmGenre $genre): static
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
            $genre->addFilm($this);
        }

        return $this;
    }

    public function removeGenre(FilmGenre $genre): static
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeFilm($this);
        }

        return $this;
    }

    public function getRating(): ?Rating
    {
        return $this->rating;
    }

    public function setRating(?Rating $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    /**
     * @return Collection<int, Seance>
     */
    public function getSeances(): Collection
    {
        return $this->seances;
    }

    public function addSeance(Seance $seance): static
    {
        if (!$this->seances->contains($seance)) {
            $this->seances->add($seance);
            $seance->setIdFilm($this);
        }

        return $this;
    }

    public function removeSeance(Seance $seance): static
    {
        if ($this->seances->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getIdFilm() === $this) {
                $seance->setIdFilm(null);
            }
        }

        return $this;
    }


}

src/Entity/FilmNote.php
<?php

namespace App\Entity;

use App\Film\Repository\FilmNoteRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmNoteRepository::class)]
class  FilmNote
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $note = null;

    #[ORM\ManyToOne(inversedBy: 'notes')]
    #[ORM\JoinColumn(nullable: false)]
    private Film $film;

    #[ORM\ManyToOne(inversedBy: 'filmNotes')]
    #[ORM\JoinColumn(nullable: false)]
    private User $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getFilm(): ?Film
    {
        return $this->film;
    }

    public function setFilm(?Film $film): static
    {
        $this->film = $film;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }
}

src/Film/Form/FilmType.php
<?php

namespace App\Film\Form;


use App\Entity\Film;
use App\Entity\FilmGenre;
use App\Entity\Rating;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\HttpFoundation\UrlHelper;
use Symfony\Component\Asset\Packages;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        if (null !== $options['data']->getImgPath()) {
            $isEmpty = false;
        } else {
            $isEmpty = true;
        }

        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre :',
            ])
            ->add('year', TextType::class,[
                'label' => 'Année :'
            ])
            ->add('genres', EntityType::class, [
                'class' => FilmGenre::class,
                'mapped' => 'true',
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => false,
                'label' => ' ',
                'by_reference' => false,
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description :',
                'attr' => array('cols' => '5', 'rows' => '10'),
            ])
            ->add('imgPath', FileType::class,
                [
                    'label' => ' ',

                    // unmapped means that this field is not associated to any entity property
                    'mapped' => false,

                    // make it optional so you don't have to re-upload the PDF file
                    // every time you edit the Product details
                    'required' => $isEmpty,
                    'data_class' => null,

                    // unmapped fields can't define their validation using attributes
                    // in the associated entity, so you can use the PHP constraint classes
                    'constraints' => [
                        new File([
                            'maxSize' => '528192k',
                            'mimeTypes' => [
                                'image/avif',
                                'image/jpeg',
                                'image/webp',
                                'image/png',
                            ],
                            'mimeTypesMessage' => 'Please upload a valid Image',
                        ])
                    ],
                ]
            )
            ->add('rating', EntityType::class, [
                'class' => Rating::class,
                'choice_label' => 'title',
                'multiple' => false,
                'expanded' => false,
                'label' => 'Rating :',
            ])
            ->add('staff_favourite', ChoiceType::class, [
                'choices' => [
                    'Oui' => true,
                    'Non' => false
                ],
                'label' => 'Coup de coeur :',
            ])
        ;

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
            'empty_data' => Film::class,
        ]);
    }

}

src/Film/Controller/Admin/AdminFilmController.php
<?php

namespace App\Film\Controller\Admin;

use App\Entity\Film;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/films', name: 'admin_films_')]
class AdminFilmController extends AbstractController
{
    #[Route('/validate/{id}', name: 'validate')]
    public function list(EntityManagerInterface $em, Film $film = null): RedirectResponse
    {
        $em->persist($film);
        $em->flush();

        return $this->redirectToRoute('films_show', ['id' => $film->getId()]);
    }
}

templates/films/edit.html.twig
{% extends app.user.getRoles[0] == 'ROLE_ADMIN' ? 'baseAdmin.html.twig' : 'baseStaff.html.twig' %}

{% form_theme form with[
    'form/template.html.twig'
]%}

{% block body %}
    <h2 class="form-film-h2">{{ is_create ? 'Ajouter un film' : 'ID ' ~ film.id }}</h2>

    <div class="form-film">
        {{ form_start(form) }}

        <div>
            {{ form_row(form.title) }}

            {{ form_row(form.year) }}

            <label for="film-input-genre" class="film_imgPath">Genre(s) :</label>
            <div class='film-input-genre'>
                <div>
                    {% for genre in film.genres %}
                        <span>{{ genre.name }}</span>
                    {% endfor %}
                </div>
                {{ ux_icon('tabler:chevron-down', {class: 'chevron-down-icon'}) }}
            </div>
            <div class='film-select-genres'>
                {{ form_row(form.genres) }}
            </div>

            {{ form_row(form.description) }}

            <a href="{{ path('films_list') }}" class="btn btn-primary">Retour</a>
        </div>
        <div>
            <label for="film_imgPath" class="film_imgPath">Image :</label>
            {% if film.imgPath %}
                <img src="{{ asset('uploads/' ~ film.getImgPath()) }}" class="img-film" width="364px" height="437px"/>
            {% else %}
                <div class="img-film empty-img"></div>
            {% endif %}

            <div class="form-file-type">
                {{ form_row(form.imgPath) }}
                <div class="input-file-type"><span>Télécharger</span></div>
            </div>

            {{ form_row(form.rating) }}

            {{ form_row(form.staff_favourite) }}

            <div class="film-form-actions">
                {% if not is_create %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('films_delete', {'id': film.id}) }}" class="btn btn-primary btn-delete-film">Supprimer</a>
                    {% endif %}
                {% else %}
                    <div class="btn-delete-film"></div>
                {% endif %}

                {{ form_end(form) }}

            </div>
        </div>
    </div>


{% endblock %}

templates/films/filmscollection.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <h2 class="collection-h2">FILMS</h2>

    <div class="collection-body-container">
    <div>
        <table class="table" id="collectionFilms">
            <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for film in films %}
                <tr>
                    <td>
                        <img src="{{ asset('uploads/' ~ film.getImgPath()) }}" class="img-film" width="250px" height="250px"/>
                        <div style="display: none !important;" id="seancesDates">{{ film.seancesDates }}</div>
                        <div style="display: none !important;" id="genreList">{{ film.genreList }}</div>
                        <div style="display: none !important;" id="seancesCities">{{ film.seancesCities }}</div>
                    </td>
                    <td class="collection-main-content-container">
                            <div class="collection-main-content">
                                <div class="collection-main-content-info">
                                    <div class="collection-main-content-title">{{ film.title }} ({{ film.year }})</div>
                                    <div>
                                        <div class="film-rating-front">{{ film.rating.getTitle }}</div>
                                        <div class="film-note">
                                            {% if film.averageNote is same as 0.0 %}
                                                {{ ux_icon('tabler:star', {class: 'star-off'}) }}
                                                {{ ux_icon('tabler:star', {class: 'star-off'}) }}
                                                {{ ux_icon('tabler:star', {class: 'star-off'}) }}
                                                {{ ux_icon('tabler:star', {class: 'star-off'}) }}
                                                {{ ux_icon('tabler:star', {class: 'star-off'}) }}
                                            {% else %}
                                                <input type="hidden" value="{{ film.averageNote }}" id="averageNoteCollection" class="averageNoteCollection">
                                            {% endif %}
                                        </div>
                                        {% if film.staffFavourite %}
                                            <img src="{{ asset('images/staff_favourite.svg') }}" alt="coup de coeur" width="130px" height="40px" class="staff-favourite-img">
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="btn btn-primary consult-seances-btn">VOIR SÉANCES</div>
                                <input type="hidden" value="{{ film.id }}" id="filmId">
                            </div>
                            <div class="collection-description">
                                <p>DESCRIPTION :</p>
                                <p>{{ film.shortDescription }}</p>
                            </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="3">Aucun film trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
        <div class="filter-city-seances">
            <div class="form-group">
                <label for="city_select_seances">Séléctionner la ville :</label>
                <select name="city_select_seances" id="city_select_seances">
                    <option value="Toutes les villes">Toutes les villes</option>
                    {% for city in cities %}
                        <option value="{{ city.title }}">{{ city.title }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group form-group-date-seance">
                <label for="date-seance">Séléctionner la date :</label>
                <input type="date" id="date-seance" name="date-seance" min="2018-01-01" max="2030-12-31" />
            </div>
            <div class="form-group form-group-places-seance">
                <label for="places-seance">Séléctionner le genre :</label>
                <select name="genres_select" id="genres_select">
                    <option value="all">Tous</option>
                    {% for genre in genres %}
                        <option value="{{ genre.name }}">{{ genre.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

    <div class="modal-seance-details">
        <div>
            <div class="button-seances-close">X</div>
        </div>
        <div class="modal-seance-info">
            <div class="modal-seance-info-column">
                <div><span class="title-detail-reservation">FILM :</span> <span class="seance-info-date"></span></div>
                <div><span class="title-detail-reservation">DATE :</span> <span class="seance-info-hour">date</span></div>
            </div>
        </div>
        <div class="modal-seance-places">
            <div>SÉANCES DISPONIBLES :</div>
            <div class="modal-places">
                <table class="table" id="collectionFilmSeances">
                    <thead>
                    <tr>
                        <th>DATE</th>
                        <th>HEURE</th>
                        <th>QUALITÉ</th>
                        <th>PRIX</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/films/listAdmin.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block body %}

    <div class="btn-create">
        {% if is_granted('create') %}
            <a href="{{ path('films_create') }}" class="btn btn-primary">Créer un film</a>
        {% endif %}
    </div>

    <table class="table" id="adminFilms">
        <thead>
            <tr>
                <th>ID</th>
                <th>Titre</th>
                <th>Année</th>
                <th>Genre</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for film in films %}
            <tr>
                <td>{{ film.id }}</td>
                <td>{{ film.title }}</td>
                <td>{{ film.year }}</td>
                <td>
                    {% if film.genres|length > 1 %}
                        {% for genre in film.genres|slice(0, (film.genres|length - 1)) %}
                            {{ genre.name }},
                        {% endfor %}
                        {% for genre in film.genres|slice((film.genres|length - 1), (film.genres|length)) %}
                            {{ genre.name }}
                        {% endfor %}
                    {% else %}
                        {% for genre in film.genres %}
                            {{ genre.name }}
                        {% endfor %}
                    {% endif %}

                </td>
                <td>
                {% if is_granted('edit', film) %}
                    <a href="{{ path('films_edit', {'id': film.id}) }}" class="btn btn-primary">Modifier</a>
                {% endif %}
                </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="3">Aucun film trouvé</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/films/listHomePage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="h1">NOUVEAUTÉS</h1>
    <div class="home-page-body">
        <div class="films-container-home">
            {% for film in films %}
                <div class="film-container-home">
                    <a href="{{ path('films_show', {'id': film.id}) }}" class="film-hover-home">VOIR LES SÉANCES</a>
                    <a href="{{ path('films_show', {'id': film.id}) }}"><img src="{{ asset('uploads/' ~ film.getImgPath()) }}" alt="{{ film.title }}" class="img-film-home"></a>
                    <a href="{{ path('films_show', {'id': film.id}) }}" class="film-title-home">{{ film.title }} ({{ film.year }})</a>
                    <p class="film-date-home">Ajouté : {{ film.dateAdd|date('d.m.Y') }}</p>
                </div>
            {% else %}
                <div>
                    <h3 colspan="3">Aucune nouveauté trouvée : revenez vers notre site plus tard pour voir les nouveautés !</h3>
                    <p>Pour voir toutes les séances veuillez entrer votre compte et accéder la page "Réserver".</p>
                </div>
            {% endfor %}
            {% if totalPages > 1 %}
                {{ include('_partials/_pagination.html.twig', {
                    currentPage: currentPage,
                    maxPage: totalPages,
                    path: 'films_list'
                }) }}
            {% endif %}
        </div>
        <div class="filter-city filter-home">
            <div class="form-group">
                <label for="city_select">Séléctionner la ville :</label>
                <select name="city_select" id="city_select">
{#                        <option value="{{ path('films_list') }}">Toutes les villes</option>#}
                    <option value="Toutes les villes">Toutes les villes</option>
                    {% for city in cities %}
{#                        <option value="{{ path('films_list', {'city': city.id}) }}">{{ city.title }}</option>#}
                        <option value="{{ city.id }}">{{ city.title }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>

{% endblock %}

templates/films/listStaff.html.twig
{% extends 'baseStaff.html.twig' %}

{% block body %}
{#    <h1>Liste des films</h1>
    {% if app.user %}
            <a class="btn btn-primary" href="{{ path('films_create') }}">Créer un film</a>
    {% endif %}#}

    <div class="btn-create">
        {% if is_granted('create') %}
            <a href="{{ path('films_create') }}" class="btn btn-primary">Créer un film</a>
        {% endif %}
    </div>

    <table class="table" id="staffFilms">
        <thead>
        <tr>
            <th>ID</th>
            <th>Titre</th>
            <th>Année</th>
            <th>Genre</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for film in films %}
            <tr>
                <td>{{ film.id }}</td>
                <td>{{ film.title }}</td>
                <td>{{ film.year }}</td>
                <td>{% for genre in film.genres %}
                        {{ genre.name }}
                    {% endfor %}
                </td>
                <td>
                    {% if is_granted('edit', film) %}
                        <a href="{{ path('films_edit', {'id': film.id}) }}" class="btn btn-primary">Modifier</a>
                    {% endif %}
                </td>
            </tr>

        {% else %}
            <tr>
                <td colspan="3">Aucun film trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/films/reservationlist.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="h1">RÉSERVER UNE SÉANCE</h1>
    <div class="home-page-body">
        <div class="films-container-home">
            {% for film in films %}
                <div class="film-container-home">
                    <a href="{{ path('films_show', {'id': film.id}) }}" class="film-hover-home">VOIR LES SÉANCES</a>
                    <a href="{{ path('films_show', {'id': film.id}) }}"><img src="{{ asset('uploads/' ~ film.getImgPath()) }}" alt="{{ film.title }}" class="img-film-home"></a>
                    <a href="{{ path('films_show', {'id': film.id}) }}" class="film-title-home">{{ film.title }} ({{ film.year }})</a>
                    <p class="film-date-home">Ajouté : {{ film.dateAdd|date('d.m.Y') }}</p>
                </div>
            {% else %}
                <div>
                    <h3 colspan="3">Aucun film trouvé</h3>
                </div>
            {% endfor %}
        </div>
        <div class="filter-city filter-reserver">
            <div class="form-group">
                <label for="city_select">Séléctionner la ville :</label>
                <select name="city_select" id="city_select">
                    <option value="all">Toutes les villes</option>
                    {% for city in cities %}
                        <option value="{{ city.id }}" >{{ city.title }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group form-group-date-seance">
                <label for="date-seance">Séléctionner la date :</label>
                <input type="date" id="date-seance" name="date-seance" min="2018-01-01" max="2030-12-31" />
            </div>
        </div>
    </div>
    {% if totalPages > 1 %}
        {{ include('_partials/_pagination.html.twig', {
            currentPage: currentPage,
            maxPage: totalPages,
            path: 'films_reservationlist'
        }) }}
    {% endif %}
{% endblock %}