src/Entity/Reservation.php
<?php

namespace App\Entity;

use AllowDynamicProperties;
use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[AllowDynamicProperties] #[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $id_user = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Seance $id_seance = null;

    #[ORM\Column]
    private ?float $cost_total = null;

    #[ORM\Column]
    private ?int $status = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_add = null;

    /**
     * @var Collection<int, ReservationDetails>
     */
    #[ORM\OneToMany(targetEntity: ReservationDetails::class, mappedBy: 'id_reservation', cascade: ['persist', 'remove'])]
    private Collection $reservationDetails;

    public function __construct()
    {
        $this->reservationDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdSeance(): ?Seance
    {
        return $this->id_seance;
    }

    public function setIdSeance(?Seance $id_seance): static
    {
        $this->id_seance = $id_seance;

        return $this;
    }

    public function getCostTotal(): ?float
    {
        return $this->cost_total;
    }

    public function setCostTotal(float $cost_total): static
    {
        $this->cost_total = $cost_total;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDateAdd(): ?\DateTimeImmutable
    {
        return $this->date_add;
    }

    public function setDateAdd(\DateTimeImmutable $date_add): static
    {
        $this->date_add = $date_add;

        return $this;
    }

    /**
     * @return Collection<int, ReservationDetails>
     */
    public function getReservationDetails(): Collection
    {
        return $this->reservationDetails;
    }

    public function addReservationDetail(ReservationDetails $reservationDetail): static
    {
        if (!$this->reservationDetails->contains($reservationDetail)) {
            $this->reservationDetails->add($reservationDetail);
            $reservationDetail->setIdReservation($this);
        }

        return $this;
    }

    public function removeReservationDetail(ReservationDetails $reservationDetail): static
    {
        if ($this->reservationDetails->removeElement($reservationDetail)) {
            // set the owning side to null (unless already changed)
            if ($reservationDetail->getIdReservation() === $this) {
                $reservationDetail->setIdReservation(null);
            }
        }

        return $this;
    }
}

src/User/Form/ContactType.php
<?php

namespace App\User\Form;

use App\Entity\Film;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class ContactType extends AbstractType
{
    public function __construct(private readonly Security $security,private readonly EntityManagerInterface $em)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options):void
    {
        $em = $this->em;
        $security = $this->security;

            $builder->add('firstname', TextType::class, [
                'label' => 'Votre prénom* :',
                'mapped' => false,
            ])
                ->add('lastname', TextType::class, [
                    'label' => 'Votre nom* :',
                    'mapped' => false,
                ])
                ->add('object', TextType::class, [
                    'label' => 'Objet* :',
                    'mapped' => false,
                ])
                ->add('email', TextType::class, [
                    'label' => 'Votre email* :',
                    'mapped' => false,
                ])
                ->add('message', TextareaType::class, [
                    'label' => 'Votre message * :',
                    'mapped' => false,
                    'attr' => array('cols' => '5', 'rows' => '10'),
                ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'allow_extra_fields' => true,
        ]);
    }
}

src/User/Form/NewPasswordType.php
<?php

namespace App\User\Form;

use App\Entity\Film;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class NewPasswordType extends AbstractType
{
    public function __construct(private readonly Security $security,private readonly EntityManagerInterface $em)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options):void
    {
        $em = $this->em;
        $security = $this->security;
        $user = $options['data'];

        $builder->add('password', PasswordType::class, [
            'label' => 'Votre nouveau mot de passe * :',
            'mapped' => false,
        ])
            ->add('email', HiddenType::class, [
            'mapped' => true,
        ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'allow_extra_fields' => true,
            'data_class' => User::class,
        ]);
    }
}

src/User/Controller/UserController.php
<?php


namespace App\User\Controller;

use App\Entity\FilmNote;
use App\Entity\Reservation;
use App\Film\Repository\FilmRepository;
use App\Repository\ReservationRepository;
use App\Seance\Repository\SeanceRepository;
use App\User\Repository\UserRepository;
use App\User\Form\UserType;
use App\User\Form\ContactType;
use App\User\Form\PasswordRestaurationType;
use App\User\Form\NewPasswordType;
use App\Entity\Seance;
use App\Entity\Film;
use App\Entity\User;
use App\Controller\MailerController;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

#[Route('/user', name: 'users_')]
class UserController extends AbstractController
{

    #[Route('/', name: 'list')]
    public function list(Security $security,UserRepository $userRepository, FilmRepository $filmRepository): Response
    {

        if ($security->isGranted('ROLE_ADMIN')) {

            $users = $userRepository->findStaff();

            return $this->render('user/listAdmin.html.twig', [
                'users' => $users,
            ]);
        } else  {
            $films = $filmRepository->findAll();

            return $this->render('films/listHomePage.html.twig', [
                'films' => $films
            ]);
        }
    }
    #[Route('/edit/{id}', name: 'edit')]
    #[Route('/create/{user}', name: 'create')]
    #[IsGranted('ROLE_ADMIN')]
    #[IsGranted('create', 'user')]
    public function edit(RouterInterface $router, Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $passwordHasher, ?User $user = null): Response
    {
        $isCreate = !$user;
        $user = $user ?? new User();
        $role = ["ROLE_WORKER"];
        $user->setRoles($role);

        $form = $this->createForm(UserType::class, $user, [
            'action' => $router->generate('users_create'),
            'attr' => ['data-turbo-frame' => '_top']
        ]);
        $form->remove('password');
        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()){
            /** @var User $user */
            $id = $_POST['current_id'];

            if($_POST['current_id'] == '') {
                $user = $form->getData();
                $plaintextPassword = $_POST['user_password_first'];

                // hash the password (based on the security.yaml config for the $user class)
                $hashedPassword = $passwordHasher->hashPassword(
                    $user,
                    $plaintextPassword
                );
                $user->setPassword($hashedPassword);

                $user->setDateAdd(new \DateTimeImmutable());

                $em->persist($user);
                $em->flush();

                $this->addFlash('success', 'L\'utilisateur a été créé' );
            } else {
                $originalUser = $em->find('App\Entity\User',$_POST['current_id']);
                $originalPassword = $originalUser->getPassword();

                $user = $form->getData();
                $oldpassword = $_POST['current_password'];
                $plaintextPassword = $_POST['user_password_first'];

                if($oldpassword !== '' AND $plaintextPassword !== ''){

                    if ($passwordHasher->isPasswordValid($originalUser, $oldpassword)) {
                        $hashedPassword = $passwordHasher->hashPassword(
                            $user,
                            $plaintextPassword
                        );

                        $originalUser->setFirstname($form->get('firstname')->getData());
                        $originalUser->setLastname($form->get('lastname')->getData());
                        $originalUser->setEmail($form->get('email')->getData());
                        $originalUser->setUsername($form->get('username')->getData());

                        $originalUser->setPassword($hashedPassword);

                        $originalUser->setDateAdd(new \DateTimeImmutable());

                        $em->persist($originalUser);
                        $em->flush();

                        $this->addFlash('success', 'L\'utilisateur a été modifié' );
                    }
/*                    else {
                        $this->addFlash('fail', 'L\'utilisateur n\'a pas été créé car l\'ancien mot de passe était pas renseigné correctement.' );
                    }*/
                } else {

                    $originalUser = $em->find('App\Entity\User',$id);

                    $originalUser->setFirstname($form->get('firstname')->getData());
                    $originalUser->setLastname($form->get('lastname')->getData());
                    $originalUser->setEmail($form->get('email')->getData());
                    $originalUser->setUsername($form->get('username')->getData());

                    $em->persist($originalUser);
                    $em->flush();
                    $this->addFlash('success', 'L\'utilisateur a été modifié' );
                }
            }

            return $this->redirectToRoute('users_list');

        }

        return $this->render('user/edit.html.twig', [
            'form' => $form,
            'is_create' => $isCreate,
            'user' => $user,
        ]);
    }

    #[Route('/myaccount/{id}', name: 'myaccount')]
    #[IsGranted('ROLE_USER')]
    #[IsGranted('create', 'user')]
    public function editMonCompte(RouterInterface $router, Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $passwordHasher, ?User $user = null): Response
    {

        if($this->getUser()->getId() == $user->getId()){
        $isCreate = !$user;
        $user = $user ?? new User();
        $role = ["ROLE_USER"];
        $user->setRoles($role);

        $form = $this->createForm(UserType::class, $user, [
            'action' => $router->generate('users_myaccount', ['id' => $user->getId()]),
            'attr' => ['data-turbo-frame' => '_top']
        ]);
        $form->remove('password');
        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()){
            /** @var User $user */
            $id = $_POST['current_id'];

            $originalUser = $em->find('App\Entity\User',$_POST['current_id']);
            $originalPassword = $originalUser->getPassword();

            $user = $form->getData();
            $oldpassword = $_POST['current_password'];
            $plaintextPassword = $_POST['user_password_first'];

            if($oldpassword !== '' AND $plaintextPassword !== ''){

                if ($passwordHasher->isPasswordValid($originalUser, $oldpassword)) {
                    $hashedPassword = $passwordHasher->hashPassword(
                        $user,
                        $plaintextPassword
                    );

                    $originalUser->setFirstname($form->get('firstname')->getData());
                    $originalUser->setLastname($form->get('lastname')->getData());
                    $originalUser->setEmail($form->get('email')->getData());
                    $originalUser->setUsername($form->get('username')->getData());

                    $originalUser->setPassword($hashedPassword);

                    $originalUser->setDateAdd(new \DateTimeImmutable());

                    $em->persist($originalUser);
                    $em->flush();

                    $this->addFlash('success', 'L\'utilisateur a été modifié' );
                }
                /*                    else {
                                        $this->addFlash('fail', 'L\'utilisateur n\'a pas été créé car l\'ancien mot de passe était pas renseigné correctement.' );
                                    }*/
            } else {

                $originalUser = $em->find('App\Entity\User',$id);

                $originalUser->setFirstname($form->get('firstname')->getData());
                $originalUser->setLastname($form->get('lastname')->getData());
                $originalUser->setEmail($form->get('email')->getData());
                $originalUser->setUsername($form->get('username')->getData());

                $em->persist($originalUser);
                $em->flush();
                $this->addFlash('success', 'L\'utilisateur a été modifié' );
            }

            return $this->redirectToRoute('users_myaccount',['id' => $id]);
        }

        return $this->render('user/monCompte.html.twig', [
            'form' => $form,
            'is_create' => $isCreate,
            'user' => $user,
        ]);
        }
        return $this->redirectToRoute('films_list');
    }

    #[Route('/reservations/{id}', name: 'reservations')]
    #[IsGranted('ROLE_USER')]
    public function listReservations(RouterInterface $router, Request $request, EntityManagerInterface $em, ?User $user = null): Response
    {
        if($this->getUser()->getId() == $user->getId()){

            $reservationsList = $user->getReservations();
            $notes = $user->getFilmNotes();

            $reservations = [];
            foreach($reservationsList as $key => $reservation){

                $reservations[$key] = $reservation;
                $seance = $reservation->getIdSeance();
                $film = $seance->getIdFilm();
                $reservations[$key]->film = $film;

templates/user/contact.html.twig
{% extends 'base.html.twig' %}

{% form_theme form with[
    'form/template.html.twig'
]%}

{% block body %}
    <div class="contact-container">
        <h2 class="h3 font-weight-normal">CONTACTEZ-NOUS</h2>
        <p>Si vous avez besoin de notre aide, n’hésitez pas à nous contacter.</p>
        <div class="contact-form-container">
            {{ form_start(form) }}
            <div>
                {{ form_row(form.firstname) }}
                {{ form_row(form.lastname) }}
                {{ form_row(form.object) }}
                {{ form_row(form.email) }}
            </div>
            <div>
                {{ form_row(form.message) }}
                <div><button type="submit" id="contact_submit" name="contact[submit]" class="btn btn-primary">Envoyer</button></div>
            </div>
            {{ form_end(form) }}

            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/user/dashboard.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block body %}

<div class="dashboard-container">
    <div class="dashboard-item">
        <div class="dashboard-item-title">
            NOMBRE DE RÉSERVATIONS AUJOURD’HUI :
        </div>
        <div>
            <img src="{{ asset('images/star_dashboard.svg') }}" alt="star dashboard">
        </div>
        <div class="dashboard-number">
            {{ nmbReservationsToday }}
        </div>
    </div>
    <div class="dashboard-item">
        <div class="dashboard-item-title">
            NOMBRE DE RÉSERVATIONS LES DERNIERS 7 JOURS :
        </div>
        <div>
            <img src="{{ asset('images/star_dashboard.svg') }}" alt="star dashboard">
        </div>
        <div class="dashboard-number">
            {{ nmbReservationsThisWeek }}
        </div>
    </div>
    <div class="dashboard-item">
        <div class="dashboard-item-title">
            NOMBRE DE RÉSERVATIONS CETTE ANNÉE :
        </div>
        <div>
            <img src="{{ asset('images/star_dashboard.svg') }}" alt="star dashboard">
        </div>
        <div class="dashboard-number">
            {{ nmbReservationsThisYear }}
        </div>
    </div>
    <div class="dashboard-item">
        <div class="dashboard-item-title">
            NOMBRE DE SÉANCES CETTE ANNÉE :
        </div>
        <div>
            <img src="{{ asset('images/star_dashboard.svg') }}" alt="star dashboard">
        </div>
        <div class="dashboard-number">
            {{ nmbSeancesThisYear }}
        </div>
    </div>
</div>
    <div class="js-dashboard"
         data-dashboard="{{ nmbReservationPerDay|serialize(format = 'json') }}">
    </div>
    <div class="dashboard-canvas-container">
        <h3>NOMBRE DE RÉSERVATIONS LES DERNIERS 7 JOURS</h3>
        <canvas id="dashboard-chart" width="1280" height="600"></canvas>
    </div>
{% endblock %}

templates/user/edit.html.twig
{% extends 'baseAdmin.html.twig' %}

{% form_theme form with[
    'form/template.html.twig'
]%}

{% block body %}
    <h2 class="form-film-h2">{{ is_create ? 'Ajouter un employé' : 'ID ' ~ user.id }}</h2>

    <div class="form-film" id="form-user">
        {{ form_start(form) }}

        <div>
            {{ form_row(form.id) }}

            {% if not is_create %}
                <input type="hidden" name="current_id" id="current_id" value="{{ user.id }}">
            {% else %}
                <input type="hidden" name="current_id" id="current_id" value="">
            {% endif %}
            {{ form_row(form.firstname) }}

            {{ form_row(form.lastname) }}


            {{ form_row(form.username) }}

            {{ form_row(form.email) }}

            <a href="{{ path('users_list') }}" class="btn btn-primary">Retour</a>
        </div>
        <div class="form-custom-column-container">
            <div class="form-custom-column">
                {% if not is_create %}
                <div class="form-group">
                    <label for="current_password">Mot de passe actuel :</label>
                    <input type="password" name="current_password" id="current_password">
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="user_password_first">Nouveau mot de passe :</label>
                    <input type="password" id="user_password_first" name="user_password_first" {{ is_create ? 'required' }}>
                </div>
                <div class="form-group">
                    <label for="user_password_second">Répétez le nouveau mot de passe :</label>
                    <input type="password" id="user_password_second" name="user_password_second" {{ is_create ? 'required' }}>
                </div>

            </div>


            <div class="film-form-actions">
                {% if not is_create %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('users_delete', {'id': user.id}) }}" class="btn btn-primary btn-delete-film">Supprimer</a>
                    {% endif %}
                {% else %}
                    <div class="btn-delete-film"></div>
                {% endif %}

                {{ form_end(form) }}

            </div>
        </div>
    </div>


{% endblock %}

templates/user/listAdmin.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block body %}
    <div class="btn-create">
        {% if is_granted('create') %}
            <a href="{{ path('users_create') }}" class="btn btn-primary">Créer un compte</a>
        {% endif %}
    </div>

    <table class="table" id="adminSeances">
        <thead>
        <tr>
            <th>ID</th>
            <th>NOM</th>
            <th>PRÉNOM</th>
            <th>EMAIL</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.email }}</td>
                <td>
                    {% if is_granted('edit', user) %}
                        <a href="{{ path('users_edit', {'id': user.id}) }}" class="btn btn-primary">Modifier</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">Aucun employé trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/user/maReservation.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">

        <h1 class="h1-espace">MON ESPACE</h1>
        <div class="my-account-menu">
            <ul class="nav nav-my-account">
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('users_myaccount', {'id': app.user.id}) }}">Mes informations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ path('users_reservations', {'id': app.user.id}) }}">Mes réservations</a>
                </li>
            </ul>
        </div>

    </div>

    <h4 class="h4-my-reservation">INFORMATIONS SUR LA RÉSERVATION :</h4>

    <div class="reservation-container">
        <div class="reservation-info-container">
            <div>CINÉMA :   {{ reservation.city.getTitle }}</div>
            <div>TITRE :   {{ reservation.film.getTitle }} ({{ reservation.film.getYear }})</div>
            <div>DATE :   {{ reservation.heure|date('d.m.Y') }}</div>
            <div>HEURE :   {{ reservation.heure|date('H:i') }}</div>
            <div>FORMAT :   {{ reservation.format }}</div>
            <div>SIÈGE(s) :
                {% if reservation.places|length > 1 %}
                    {% for place in reservation.places|slice(0, (reservation.places|length - 1)) %}
                        {{ place }},
                    {% endfor %}
                    {% for place in reservation.places|slice((reservation.places|length - 1), (reservation.places|length)) %}
                        {{ place }}
                    {% endfor %}
                {% else %}
                    {% for place in reservation.places %}
                        {{ place }}
                    {% endfor %}
                {% endif %}
            </div>
            <div>TOTAL COST TTC : {{ reservation.costTotal }}€</div>
        </div>
        <div class="reservation-actions">
            <div class="reservation-actions-0">
                <a href="{{ path('seances_editreservation', {'id': reservation.getIdSeance.id, 'reservationId' : reservation.id}) }}" class="btn btn-primary">MODIFIER<br>LA RÉSERVATION</a>
                <div class="btn btn-primary cancel-reservation">ANNULER<br>LA RÉSERVATION</div>
            </div>
            <a href="{{ path('users_reservations', {'id': app.user.id}) }}" class="btn btn-primary">VOIR TOUTES MES RÉSERVATIONS</a>
        </div>
    </div>
    <div class="modal-cancellation-confirmation">
        <div><strong>Vous êtes sûr(e)<br>que vous vous voulez annuler cette réservation?</strong></div>
        <div class="cancellation-actions">
            <div class="btn btn-primary cancel-cancellation">NON</div>
            <a href="{{ path('users_cancelreservation', {'id': reservation.id}) }}" class="btn btn-primary">OUI</a>
        </div>
    </div>


{% endblock %}

templates/user/mesReservations.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">

        <h1 class="h1-espace">MON ESPACE</h1>
        <div class="my-account-menu">
            <ul class="nav nav-my-account">
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('users_myaccount', {'id': app.user.id}) }}">Mes informations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ path('users_reservations', {'id': app.user.id}) }}">Mes réservations</a>
                </li>
            </ul>
        </div>

    </div>

    <table class="table my-reservations-table" id="adminSeances">
        <thead>
        <tr>
            <th>TITRE</th>
            <th>DATE</th>
            <th>HEURE</th>
            <th>FORMAT</th>
            <th>SIÈGE(S)</th>
            <th>ACTION/VOTRE NOTE</th>
        </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.film.getTitle }}</td>
                <td>{{ reservation.heure|date('d.m.Y') }}</td>
                <td>{{ reservation.heure|date('H:i') }}</td>
                <td>{{ reservation.format }}</td>
                <td>
                    {% if reservation.places|length > 1 %}
                        {% for place in reservation.places|slice(0, (reservation.places|length - 1)) %}
                            {{ place }},
                        {% endfor %}
                        {% for place in reservation.places|slice((reservation.places|length - 1), (reservation.places|length)) %}
                            {{ place }}
                        {% endfor %}
                    {% else %}
                        {% for place in reservation.places %}
                            {{ place }}
                        {% endfor %}
                    {% endif %}
                </td>
                <td>
                    {% if reservation.passed == 0 and reservation.status == 0 %}
                        <a href="{{ path('users_reservation', {'id': reservation.id}) }}" class="btn btn-primary">Voir la réservation</a>
                    {% elseif reservation.passed == 0 and reservation.status == 0 %}
                        <a href="{{ path('users_reservation', {'id': reservation.id}) }}" class="btn btn-primary">Voir la réservation</a>
                    {% elseif reservation.passed == 1 and reservation.status == 0 %}
                        <div>ANNULÉE</div>
                        <a href="{{ path('films_show', {'id': reservation.film.getId}) }}" class="btn btn-primary">Faire une autre réservation</a>
                    {% elseif reservation.passed == 1 and reservation.status == 1 %}
                        {% if null is not same as reservation.note %}
                            <div class="note-stars-container">
                                <input type="hidden" value="{{ reservation.film.id }}" id="filmId">
                                <input type="hidden" value="{{ reservation.note.id }}" id="gradeId">
                                <input type="hidden" value="{{ reservation.note.note }}" id="grade">
                                {{ ux_icon('tabler:star-filled', {'data-grade': 1}) }}
                                {{ ux_icon('tabler:star-filled', {'data-grade': 2}) }}
                                {{ ux_icon('tabler:star-filled', {'data-grade': 3}) }}
                                {{ ux_icon('tabler:star-filled', {'data-grade': 4}) }}
                                {{ ux_icon('tabler:star-filled', {'data-grade': 5}) }}
                            </div>
                        {% else %}
                            <a href="#" class="btn btn-primary add-note">Noter le film</a>
                            <div class="note-stars-container">
                                <input type="hidden" value="{{ reservation.film.id }}" id="filmId">
                                {{ ux_icon('tabler:star-filled', {class: 'star-off', 'data-grade': 1}) }}
                                {{ ux_icon('tabler:star-filled', {class: 'star-off', 'data-grade': 2}) }}
                                {{ ux_icon('tabler:star-filled', {class: 'star-off', 'data-grade': 3}) }}
                                {{ ux_icon('tabler:star-filled', {class: 'star-off', 'data-grade': 4}) }}
                                {{ ux_icon('tabler:star-filled', {class: 'star-off', 'data-grade': 5}) }}
                            </div>
                        {% endif %}
                    {% elseif reservation.passed == 1 and reservation.status == 1 and null is not same as(reservation.note) %}
                        <div>{{ reservation.note.getNote }}</div>
                    {% elseif reservation.status == 3 %}
                        <div>ANNULÉE</div>
                        <a href="{{ path('films_show', {'id': reservation.film.getId}) }}" class="btn btn-primary">Faire une autre réservation</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">Aucune réservation trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}